/*
 * Copyright 2014-2016 Peng Wan <phylame@163.com>
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *     http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

package pw.phylame.jem.epm

import pw.phylame.jem.core.MapDelegate
import java.util.zip.Deflater

open class CommonConfig(val map: Map<String, Any>) {
}

open class ZipParseConfig(map: Map<String, Any>) : CommonConfig(map) {

}

open class ZipMakeConfig(map: Map<String, Any>) : CommonConfig(map) {
    val zipMethod: Int by MapDelegate(map, Deflater.DEFLATED)

    val zipLevel: Int by MapDelegate(map, Deflater.DEFAULT_COMPRESSION)

    val zipComment: String by MapDelegate(map, "Generated by Jem Formats v")
}